/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registration;

import Default_Tables.TableCall;
import View_Table.Data_Input;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author prakh
 */
public class Registration_Workshop extends javax.swing.JFrame {

    /**
     * Creates new form WorkshopInput
     */
    public Registration_Workshop() {
        setTitle("Workshop Registration");
        initComponents();
        fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fn_text = new javax.swing.JTextField();
        ln_text = new javax.swing.JTextField();
        usn_text = new javax.swing.JTextField();
        college = new javax.swing.JTextField();
        cn_text = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        wid = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        usn = new javax.swing.JLabel();
        cg = new javax.swing.JLabel();
        cn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        ws_sel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fn_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn_textActionPerformed(evt);
            }
        });

        ln_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ln_textActionPerformed(evt);
            }
        });

        usn_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usn_textActionPerformed(evt);
            }
        });

        college.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeActionPerformed(evt);
            }
        });

        cn_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cn_textActionPerformed(evt);
            }
        });

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        wid.setText("Workshop Name");

        fn.setText("First Name");

        ln.setText("Last Name");

        usn.setText("USN");

        cg.setText("College");

        cn.setText("Contact");

        jLabel8.setText("Please Enter the Values for registering");

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        ws_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ws_selActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(submit)
                        .addGap(52, 52, 52)
                        .addComponent(cancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ln, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wid))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cn_text)
                            .addComponent(college)
                            .addComponent(usn_text)
                            .addComponent(ln_text)
                            .addComponent(fn_text)
                            .addComponent(ws_sel, 0, 135, Short.MAX_VALUE))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fn_text, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fn))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ln))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usn_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(college, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cn_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wid)
                    .addComponent(ws_sel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(submit))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            System.out.println(ws_sel.getSelectedItem().toString());
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms project?zeroDateTimeBehavior=convertToNull","root","");
            String sql="SELECT WORKSHOPID FROM WORKSHOP WHERE WORKSHOPName='"+ws_sel.getSelectedItem().toString()+"';";
            PreparedStatement ps=(PreparedStatement) con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            String wid="";
            if(rs.next()){
            wid=rs.getObject(1).toString();}
            System.out.println(wid);
            sql="SELECT COUNT(USN) FROM PARTICIPANT WHERE USN='"+usn_text.getText()+"';";
            ps= (PreparedStatement) con.prepareStatement(sql);
            rs=ps.executeQuery();
            if(!usn_text.getText().equals("")&& !college.getText().equals("") && !cn_text.getText().equals("") && !fn_text.getText().equals("")){
            if(rs.next()){
                System.out.println(rs.getObject(1).toString());
              if(rs.getObject(1).toString().equals("1"))
               {
                if(!usn_text.getText().equals("")){
                sql="SELECT COUNT(*) FROM PARTICIPATION WHERE USN='"+usn_text.getText()+"'AND WORKSHOPID='"+wid+"';";
                ps= (PreparedStatement) con.prepareStatement(sql);
                rs=ps.executeQuery();
                rs.next();
                System.out.println(rs.getObject(1).toString());
                if(rs.getObject(1).toString().equals("0"))
                {
                sql="INSERT INTO PARTICIPATION VALUES('"+usn_text.getText()+"',null,'"+wid+"',null,'0');";
                ps= (PreparedStatement) con.prepareStatement(sql);
                ps.execute();
                sql="UPDATE WORKSHOP set registrations=registrations+1 where WORKSHOPID='"+wid+"';";
                ps=(PreparedStatement) con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null,"Registered Successfully");
                }}
                else
                {
                    JOptionPane.showMessageDialog(null,"Registration Failure");
                }
              }
              else if(rs.getObject(1).toString().equals("0"))
              {
                sql="INSERT INTO PARTICIPANT VALUES('"+usn_text.getText()+"','"+ ln_text.getText()+"','"+fn_text.getText()+"','"+cn_text.getText()+"','"+college.getText()+"');";
                ps= (PreparedStatement) con.prepareStatement(sql);
                ps.execute();
                sql="INSERT INTO PARTICIPATION VALUES('"+usn_text.getText()+"',null,'"+wid+"',null,0);";
                ps= (PreparedStatement) con.prepareStatement(sql);
                ps.execute();
                sql="UPDATE WORKSHOP set registrations=registrations+1 where WORKSHOPID='"+wid+"';";
                ps=(PreparedStatement) con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null,"Registered Successfully");  
              }
            }
         }
        else
            {
                JOptionPane.showMessageDialog(null,"Registration Failure! Check Fields!");
            }        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        try{
            this.setVisible(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_cancelActionPerformed

    private void cn_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cn_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cn_textActionPerformed

    private void collegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeActionPerformed

    private void usn_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usn_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usn_textActionPerformed

    private void ln_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ln_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ln_textActionPerformed

    private void fn_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn_textActionPerformed

    private void ws_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ws_selActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ws_selActionPerformed
public void fill()
    {
        try{
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms project?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement ps= (PreparedStatement) con.prepareStatement("SELECT * FROM WORKSHOP");
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                String field =rs.getString("WorkshopName");
                ws_sel.addItem(field);
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registration_Workshop().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel cg;
    private javax.swing.JLabel cn;
    private javax.swing.JTextField cn_text;
    private javax.swing.JTextField college;
    private javax.swing.JLabel fn;
    private javax.swing.JTextField fn_text;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ln;
    private javax.swing.JTextField ln_text;
    private javax.swing.JButton submit;
    private javax.swing.JLabel usn;
    private javax.swing.JTextField usn_text;
    private javax.swing.JLabel wid;
    private javax.swing.JComboBox<String> ws_sel;
    // End of variables declaration//GEN-END:variables
}
